# -*- coding: utf-8 -*-
"""Shot data for SVIF ad 2, working title "Fyrsti dagurinn" (The first day).
Times are seconds on the reference track's beat grid (80.7 BPM, beat = 0.743 s).
E = Element ids in the Higgsfield workspace (svif-fyrsti-dagurinn project).
"""
E = {
 "hrefna":"e19c5ead-1a48-4632-87c6-2b8eeef2c1d1",
 "kari":"e806b69e-f2de-4419-8fb8-a3da29b82d24",
 "asi":"12fa9a4b-abe6-4612-8765-c9ef22f09142",
 "snati":"066c1650-8bf7-4233-86df-edd1d2e00fce",
 "pipari":"86619b44-254a-4c04-b18d-b8b12d0d5bc4",
 "loc_hus":"63e39a94-542c-437e-9670-33e8d543f63b",
 "loc_gangur":"186b6bf5-3d6c-498b-a240-166b8632ddba",
 "loc_bad":"d26832b4-aece-4d61-9ae6-d0c26416df2c",
 "loc_stofa":"0b604cf0-26cc-4622-8b61-be43dc8e27dc",
 "loc_eldhus":"ae5d9d4c-4fee-4c00-a71f-3098f48d7f75",
 "prop_b-klingur":"1adb3de8-893e-4fed-b21f-5ed52bc89ae3",
}
LOOK = ("Shot on ARRI Alexa 35, 24 fps, 180 degree shutter, light 35mm film grain, Kodak Vision3 feel, "
        "warm late-summer afternoon light, natural matte skin with visible pores, cinematic realism, vertical 9:16.")

# (id, t_in, t_out, beat/hit, slug, action, elements, camera, prompt, model, sfx, service)
# model: K = Kling 3.0 pro (multi-shot / physical gags), S = Seedance 2.5 omni (water, glass, paint physics), V = Veo 3 (faces, reactions)
SHOTS = [
 ("1", 0.00, 1.63, "hook frame = loop frame", "EXT. HOUSE, GATE - AFTERNOON",
  "Locked wide. The family stands at the garden gate with the estate agent; the house looks lovely. The lavender SVIF book is already lying on the doormat, unnoticed. This exact frame is also the last frame of the film.",
  ["loc_hus","hrefna","kari","asi","snati","prop_b-klingur"], "24mm f/8 static, eye level, house fills the top two thirds",
  "@loc_hus. Wide static shot, @hrefna, @kari, @asi and @snati stand at the garden gate facing the house with their backs half to camera, an estate agent in a grey suit beside them holding out a key, @prop_b-klingur lies flat on the brown doormat by the front door, nobody looks at it, warm afternoon sun from the left, long shadows on the path.", "K", "birds, distant traffic, a lawnmower far away", ""),
 ("2", 1.63, 3.00, "rise into the hit", "EXT. GATE - CU HANDS",
  "Close on Kári's open palm rising into frame, exactly like the newspaper rising in the reference.",
  ["kari"], "85mm f/2, locked, hand enters from below",
  "Close-up of the open palm of @kari rising slowly into frame from the bottom, afternoon sun on the skin, blurred white corrugated-iron house behind, shallow depth of field.", "V", "none, music only", ""),
 ("3", 3.00, 4.34, "HIT 3.00 key clink", "EXT. GATE - CU KEY",
  "A brass key drops into the palm on the hit. His thumb closes over it. Hold.",
  ["kari"], "85mm f/2 locked",
  "Close-up, a single brass house key drops from above into the open palm of @kari and lands with a small bounce, his thumb closes over it, warm afternoon light, shallow depth of field, blurred house behind.", "S", "KEY CLINK on 3.00 (the first sound effect of the film)", ""),
 ("4", 4.34, 5.78, "HIT 4.34 door", "EXT./INT. FRONT DOOR",
  "The green front door swings open on the hit. Ási and Snati burst past the adults' legs into the house.",
  ["loc_gangur","asi","snati","kari","hrefna"], "35mm f/4, low, from inside the hallway toward the door",
  "@loc_gangur. From inside the hallway looking at the closed green front door, the door swings open fast toward camera, @asi and @snati burst through the doorway past the legs of @kari and @hrefna and run toward camera, bright afternoon light flooding in behind them.", "K", "DOOR SWING + paws on parquet", ""),
 ("5", 5.78, 7.27, "HIT 5.78 eyes", "INT. HALLWAY - MACRO HREFNA",
  "Hrefna's face, slow push into her eyes as they widen with joy. The reference's eye shot.",
  ["hrefna"], "85mm f/2 slow push to macro",
  "Close-up of the face of @hrefna standing in a sunlit hallway, slow continuous push-in toward her grey-blue eyes, her eyes widen with delight and a smile starts, warm window light on one side of her face, natural skin, shallow focus.", "V", "soft breath in", ""),
 ("6", 7.27, 8.78, "quiet", "INT. HALLWAY TO LIVING ROOM - STEADICAM",
  "Slow walk-in through the hallway into the living room. Dust in the light. Everything looks perfect. Snati sniffs the boxes.",
  ["loc_stofa","snati"], "24mm f/4 slow steadicam forward",
  "@loc_stofa. Slow smooth steadicam move forward through a doorway into the living room, dust motes in the warm afternoon light from the big window, @snati sniffs a cardboard moving box, the room looks clean and inviting.", "K", "footsteps, dog sniff", ""),
 ("7", 8.78, 10.26, "foreshadow", "INT. LIVING ROOM - LIGHT SWITCH",
  "Kári flicks the light switch. The bare bulb flickers once, then holds. He shrugs: fine.",
  ["loc_stofa","kari"], "50mm f/2.8 locked, switch and bulb both in frame",
  "@loc_stofa. @kari flicks a white wall light switch, the bare pendant bulb above him flickers once and then stays on, he glances up at it and shrugs, warm afternoon light.", "K", "switch click, bulb buzz", "Rafvirki"),
 ("8", 10.26, 11.87, "HIT 10.26 lid", "INT. BATHROOM - TOILET LID",
  "Kári lifts the toilet lid on the hit and leans in to inspect. Pause.",
  ["loc_bad","kari"], "35mm f/2.8 low, from beside the toilet",
  "@loc_bad. @kari lifts the white toilet lid with one finger and leans over the bowl to look inside with a suspicious squint, low angle from beside the toilet, avocado-green tiles, warm ceiling light.", "K", "LID KNOCK on 10.26, water gurgle rising", "Pípari"),
 ("9", 11.87, 13.49, "TRIPLE HIT 11.87 / 12.05 / 12.26", "INT. BATHROOM - ERUPTION",
  "The toilet erupts: three gushes of water straight up into his face, one per hit. The plumber gag.",
  ["loc_bad","kari"], "35mm f/2.8 locked, same angle as 8",
  "@loc_bad. @kari is bent over the open toilet bowl, suddenly a column of clear water erupts upward out of the bowl straight into his face, then a second and a third burst, water everywhere, he recoils with his eyes squeezed shut, avocado-green tiles, warm ceiling light, slow-motion water droplets.", "S", "three WATER BURSTS exactly on 11.87, 12.05, 12.26", "Pípari"),
 ("10", 13.49, 14.35, "HIT 13.47 deadpan", "INT. BATHROOM - KÁRI DRENCHED",
  "Kári, soaked, deadpan straight into the lens. One drop falls from his nose.",
  ["kari"], "85mm f/2 locked, dead centre",
  "Close-up of @kari soaking wet, water dripping from his beard and hair, staring straight into the camera with a flat deadpan expression, one drop of water falling from the tip of his nose, avocado-green tiles behind him, warm light.", "V", "single DRIP", "Pípari"),
 ("11", 14.35, 15.14, "energy lifts 14.35", "EXT. GARDEN - ÁSI KICKS",
  "Ási in the garden kicks a football hard toward the house.",
  ["loc_hus","asi"], "35mm f/4 low, ball travels toward camera-right",
  "@loc_hus, in the small front garden, @asi runs up and kicks a football as hard as he can toward the house, low angle from the grass, afternoon sun, the ball leaves frame fast.", "K", "ball THUMP", "Gler"),
 ("12", 15.14, 15.93, "HIT 15.14 glass", "INT. LIVING ROOM - WINDOW SHATTERS",
  "The living-room window shatters inward on the hit, glass flying toward camera, the ball bouncing across the parquet.",
  ["loc_stofa"], "50mm f/2.8 locked, window centre",
  "@loc_stofa. The big living-room window shatters inward as a football comes through it, glass fragments flying toward the camera in slow motion, the ball bounces across the parquet floor, warm afternoon light through the broken pane.", "S", "GLASS SHATTER on 15.14", "Gler"),
 ("13", 15.93, 17.46, "reaction", "EXT. GARDEN - GUILTY ÁSI",
  "Ási's guilty face framed in the broken window, hands behind his back. Snati beside him with ears down.",
  ["asi","snati","loc_hus"], "50mm f/2.8 from inside through the hole",
  "Seen from inside through a jagged hole in a broken window, @asi stands in the garden outside with his hands behind his back and a wide-eyed guilty face, @snati sits beside him with his ears flattened, afternoon sun.", "V", "tiny glass tinkle", "Gler"),
 ("14", 17.46, 18.97, "gurgle", "INT. KITCHEN - THE SINK",
  "Hrefna turns on the tap. The sink gurgles, and brown water rises instead of draining.",
  ["loc_eldhus","hrefna"], "35mm f/2.8 high angle over her shoulder",
  "@loc_eldhus. @hrefna turns the chrome mixer tap on over the steel sink, the drain gurgles and murky brown water rises up out of the plughole and fills the sink instead of draining, she pulls her hand back, over-the-shoulder high angle, warm window light.", "S", "GURGLE rising, tap squeak", "Stíflulosun"),
 ("15", 18.97, 20.55, "energy dip 19", "INT. KITCHEN - HREFNA'S LOOK",
  "Hrefna's slow look toward the hallway, where the wet husband is. Snati starts lapping the brown sink water. Hold.",
  ["hrefna","snati","loc_eldhus"], "50mm f/2.8 locked",
  "@loc_eldhus. @hrefna turns her head slowly toward the doorway with a flat unimpressed expression, behind her @snati stands on his hind legs with his front paws on the counter lapping water from the sink, warm window light.", "K", "lapping, drip", "Stíflulosun"),
 ("16", 20.55, 23.06, "build", "INT. LIVING ROOM - BULB IN MOUTH",
  "Kári on a stepladder under the pendant, bulb held in his teeth, screwdriver in the fitting. Hrefna, Ási and Snati on the sofa behind, watching TV.",
  ["loc_stofa","kari","hrefna","asi","snati"], "24mm f/4 low wide, ladder foreground, sofa background",
  "@loc_stofa. @kari stands on a wooden stepladder under the ceiling pendant with a light bulb held sideways in his teeth and a screwdriver in the lamp fitting, in the background @hrefna, @asi and @snati sit on the grey sofa watching the TV, low wide angle, warm afternoon light.", "K", "screwdriver scrape, TV murmur", "Rafvirki"),
 ("17", 23.06, 25.47, "build to HIT 25.47", "INT. LIVING ROOM - CU KÁRI",
  "Close: he takes the bulb from his teeth, screws it in, it glows, he grins. Then the hit: a blue flash.",
  ["kari"], "50mm f/2.8 handheld micro-movement",
  "Close-up of @kari on a stepladder taking a light bulb from between his teeth and screwing it into a ceiling pendant fitting, it lights up warm, he grins proudly, then a sudden bright blue-white electrical flash from the fitting.", "K", "bulb hum, then BZZT FLASH on 25.47", "Rafvirki"),
 ("18", 25.47, 27.05, "HIT 25.47 blackout, HIT 26.26", "INT. LIVING ROOM - SOFA BLACKOUT",
  "Cut to the sofa: lights flicker, the TV dies, everything goes dark except window light. Three faces turn toward the ladder in unison.",
  ["loc_stofa","hrefna","asi","snati"], "35mm f/2.8 locked, sofa centred",
  "@loc_stofa. @hrefna, @asi and @snati sit on the grey sofa lit by the TV, the ceiling light flickers twice and dies, the TV screen goes black, the room drops to dim window light only, all three turn their heads slowly toward the left in unison.", "K", "power-down WHINE on 26.26", "Rafvirki"),
 ("19", 27.05, 27.82, "one beat", "INT. LIVING ROOM - SILHOUETTE",
  "Kári's silhouette on the ladder, hair standing straight up, a wisp of smoke from the fitting.",
  ["kari","loc_stofa"], "35mm f/4 backlit by the window",
  "@loc_stofa. @kari stands on the stepladder in silhouette against the bright window, his hair standing straight up, a thin wisp of smoke rising from the ceiling fitting above him, screwdriver still in hand.", "V", "faint sizzle", "Rafvirki"),
 ("20", 27.82, 29.30, "build to HIT 29.30", "INT. LIVING ROOM - PAINT CAN",
  "Kári on the ladder rolls paint on the wall; an open can of lavender paint wobbles on the top step. Snati sits directly below.",
  ["loc_stofa","kari","snati"], "35mm f/4 low, can and dog in frame",
  "@loc_stofa. @kari on a stepladder rolls cream paint onto the wall with a roller, an open can of pale lavender paint on the top step of the ladder wobbles with every stroke, @snati sits on the floor directly below the ladder looking up, low angle.", "K", "roller squelch, can wobble", "Málari"),
 ("21", 29.30, 30.79, "HIT 29.30 splash", "INT. LIVING ROOM - DOG GETS PAINTED",
  "The can tips and pours lavender paint over Snati. The dog looks up, now the colour of the SVIF book.",
  ["snati","loc_stofa"], "50mm f/2.8 locked on the dog",
  "@loc_stofa. A can of pale lavender paint tips off the top of a stepladder and pours over @snati sitting on the floor below, the paint runs down his fur, he looks up at camera with a calm blinking face, now coated in lavender, warm light.", "S", "SPLAT on 29.30, drip", "Málari"),
 ("22", 30.79, 31.51, "one beat", "INT. LIVING ROOM - SHAKE",
  "Snati shakes. Lavender paint sprays Hrefna's sweater.",
  ["snati","hrefna","loc_stofa"], "35mm f/4 locked",
  "@loc_stofa. @snati, coated in lavender paint, shakes his whole body hard, paint droplets spray outward in slow motion onto the mustard-yellow sweater of @hrefna standing beside him, she freezes with her arms out.", "S", "wet SHAKE flutter", "Málari"),
 ("23", 31.51, 32.90, "HIT 31.49 board, 32.21", "INT. LIVING ROOM - FLOORBOARD",
  "Hrefna steps on a loose parquet board; it springs up and smacks Kári's shin.",
  ["loc_stofa","hrefna","kari"], "35mm f/4 low floor-level",
  "@loc_stofa. Floor-level shot, @hrefna steps on the end of a loose parquet floorboard, the other end springs up and smacks @kari on the shin as he walks past, he hops on one leg holding his shin, warm light.", "K", "BOARD SNAP on 31.49, THWACK on 32.21", "Gólfefni"),
 ("24", 32.90, 34.32, "HIT 32.90 rail", "INT. LIVING ROOM - CURTAIN RAIL",
  "Kári grabs the old curtain to steady himself. The whole rail comes down on his head.",
  ["loc_stofa","kari"], "50mm f/2.8 locked",
  "@loc_stofa. @kari hopping on one leg grabs the faded brown curtain by the window to steady himself, the old curtain rail tears out of the wall and the rail and curtains collapse over his head and shoulders, he stands there draped in curtain.", "K", "RAIL CRACK on 32.90, fabric whump", "Gluggatjöld"),
 ("25", 34.32, 35.67, "build", "INT. KITCHEN - SMOKE",
  "Ási on a stool at the stove; a pan is smoking hard. He fans it with a pizza box. The smoke alarm starts to chirp.",
  ["loc_eldhus","asi"], "35mm f/2.8 locked",
  "@loc_eldhus. @asi stands on a kitchen stool at the stove where a frying pan is pouring out grey smoke, he fans the smoke with a flat pizza box, the round smoke detector on the ceiling blinks red, warm window light through haze.", "K", "sizzle, alarm CHIRP CHIRP", "Eldvarnir"),
 ("26", 35.67, 36.99, "HIT 35.67 shriek", "INT. KITCHEN - ALARM",
  "The alarm shrieks. Hrefna on a chair twists it off the ceiling; the battery drops into the brown sink water.",
  ["loc_eldhus","hrefna"], "35mm f/2.8 low angle up at the ceiling",
  "@loc_eldhus. @hrefna stands on a kitchen chair twisting a shrieking round smoke detector off the ceiling, it comes loose and a square battery drops out of it and falls toward the sink, low angle, smoke haze, warm light.", "K", "ALARM SHRIEK on 35.67, plop", "Eldvarnir"),
 ("27", 36.99, 38.31, "beat", "INT. LIVING ROOM - COLD",
  "Kári bleeds the radiator: it coughs cold air. Ási breathes visible fog indoors. Everyone is now in coats.",
  ["loc_stofa","kari","asi"], "50mm f/2.8 locked",
  "@loc_stofa. @kari kneels at the radiator under the window turning a bleed valve with a key, the valve hisses cold air into his face, beside him @asi in his blue rain jacket zipped up breathes out a visible cloud of fog, dim window light.", "K", "HISS, shiver", "Gólfhiti"),
 ("28", 38.31, 39.57, "HIT 38.31 plank", "EXT. SIDE DECK - PLANK",
  "Kári steps out onto the wooden deck; a plank gives way and his leg goes through to the thigh.",
  ["loc_hus","kari"], "35mm f/4 low from deck level",
  "@loc_hus, the weathered wooden side deck, @kari steps out onto the deck with a coffee mug, a grey rotten plank snaps under his boot and his leg drops through the deck up to the thigh, coffee sloshes, afternoon sun, low angle.", "K", "PLANK CRACK on 38.31, coffee slosh", "Pallar"),
 ("29", 39.57, 40.82, "drip", "INT. LIVING ROOM - CEILING DRIP",
  "Water drips from the ceiling onto the sofa. Hrefna slides a bowl under it. Plink.",
  ["loc_stofa","hrefna"], "50mm f/2.8 locked, drip and bowl",
  "@loc_stofa. A water drop falls from a dark stain on the ceiling onto the grey sofa, @hrefna slides a white kitchen bowl under the drip without looking up, the next drop lands in the bowl, dim light.", "K", "PLINK on 40.19", "Þak"),
 ("30", 40.82, 42.84, "HIT 40.82 LOW POINT, hold 3 beats", "INT. LIVING ROOM - THE FAMILY PORTRAIT",
  "Locked wide: all four on the sofa in coats under the dead bulb. Drip into the bowl. Lavender dog. Kári's hair up, curtain over his shoulder. Cardboard taped over the window. They stare dead into the lens. Hold.",
  ["loc_stofa","hrefna","kari","asi","snati"], "35mm f/4 locked, symmetrical, lens at sofa height",
  "@loc_stofa. Symmetrical locked wide shot, @hrefna, @kari, @asi and @snati sit in a row on the grey sofa all wearing coats indoors, @kari soaking wet with his hair standing up and a curtain draped over one shoulder, @snati coated in lavender paint, a white bowl on the floor catching drips from the ceiling, cardboard taped over the broken window, the bare bulb dead, all four stare straight into the camera with flat deadpan faces, dim cold window light.", "K", "drip, drip, one dog sigh. Music ducks slightly", ""),
 ("31", 42.84, 44.40, "HIT 42.84 letterbox", "INT. HALLWAY - THE BOOK ARRIVES",
  "The letterbox flap rattles; the lavender SVIF book slides through and lands on the doormat.",
  ["loc_gangur","prop_b-klingur"], "35mm f/2.8 low from the mat, door in frame",
  "@loc_gangur. Low angle from floor level by the doormat, the brass letterbox flap in the green front door rattles open and @prop_b-klingur slides through the slot and drops flat onto the brown doormat, cover facing up, warm light through the door glass.", "S", "LETTERBOX CLACK on 42.84, paper slap", ""),
 ("32", 44.40, 45.58, "HIT 44.40 dog", "INT. HALLWAY - SNATI DELIVERS",
  "Snati, still lavender, trots to the mat, picks the book up gently in his mouth and carries it to the living room.",
  ["loc_gangur","snati","prop_b-klingur"], "35mm f/2.8 low, tracking the dog",
  "@loc_gangur. @snati coated in lavender paint trots to the doormat, picks up @prop_b-klingur gently in his mouth and turns to carry it toward the living room, low tracking shot at dog height, warm light.", "K", "paws, soft paper", ""),
 ("33", 45.58, 47.07, "HIT 45.56 cover", "INT. LIVING ROOM - THE COVER",
  "Ási takes the book from the dog. The cover fills the frame: SVIF, Velkomin í nýja heimilið þitt.",
  ["asi","prop_b-klingur"], "50mm f/2.8 top-down over his hands",
  "Top-down close-up of the small hands of @asi holding @prop_b-klingur flat, the lavender cover filling most of the frame, a few lavender paw prints on the floor beside it, soft light.", "K", "page rustle", ""),
 ("34", 47.07, 50.11, "4 beats 47.07 47.81 48.53 49.30, one page per beat", "INT. LIVING ROOM - PAGES",
  "Ási flips pages, one per beat: a plumber page, an electrician page, a glazier page, a painter page. Hrefna and Kári lean in from both sides.",
  ["asi","hrefna","kari","prop_b-klingur"], "50mm f/2.8 locked top-down",
  "Top-down close-up, @asi flips through the pages of @prop_b-klingur open on his lap, one page turn after another, each spread a clean ad layout with a photo and a discount box, the heads of @hrefna and @kari lean in from the left and right edges of frame, soft light.", "K", "four PAGE FLIPS on the beats", "Import the real pages as references so the model never invents ads"),
 ("35", 50.11, 50.90, "one beat", "INT. LIVING ROOM - THE CALL",
  "Hrefna on the phone, book in her other hand, the first smile of Act 2.",
  ["hrefna","prop_b-klingur"], "85mm f/2 locked",
  "Close-up of @hrefna holding a phone to her ear and @prop_b-klingur open in her other hand, she listens, nods and smiles with relief, dim room, window light on her face.", "V", "phone ring tone, muffled voice", ""),
 ("36", 50.90, 51.64, "one beat", "EXT. FRONT DOOR - DOORBELL",
  "Kári opens the front door. The plumber stands there with his toolbox; a white van behind him at the gate.",
  ["loc_hus","kari","pipari"], "35mm f/4 from inside the hallway",
  "@loc_hus seen from inside the open front door, @kari opens the door and @pipari stands on the step holding a red metal toolbox and raising two fingers in a casual greeting, a plain white van parked at the gate behind him, afternoon sun.", "K", "DOORBELL on 50.90", "Pípari"),
 ("37", 51.64, 52.43, "one beat", "INT. BATHROOM - FIXED",
  "The plumber under the toilet, wrench turn, thumbs up to camera. Lid closes.",
  ["loc_bad","pipari"], "35mm f/2.8 low",
  "@loc_bad. @pipari kneels beside the toilet giving a pipe at the back one last turn with a wrench, then turns to camera and gives a thumbs up, low angle, avocado tiles, warm light.", "K", "wrench CLICK, lid tap", "Pípari"),
 ("38", 52.43, 53.17, "one beat", "INT. HALLWAY - BREAKER",
  "An electrician flips the main breaker; the lights bloom back on down the hallway.",
  ["loc_gangur"], "35mm f/2.8 locked",
  "@loc_gangur. A woman electrician in a grey work jacket flips a breaker switch in an open fuse box on the hallway wall, the bare bulb and the living-room lights beyond bloom back on one after another, warm light returning.", "K", "BREAKER CLUNK on 52.43, hum", "Rafvirki"),
 ("39", 53.17, 53.92, "one beat", "INT. LIVING ROOM - NEW GLASS",
  "A glazier slides a new pane into the window frame. Ási watches with the football under his arm.",
  ["loc_stofa","asi"], "35mm f/4 locked",
  "@loc_stofa. A glazier in a blue work jacket slides a new clean pane of glass into the living-room window frame with suction cups, @asi watches from beside him holding a football under his arm, afternoon light.", "K", "glass SET, suction pop", "Gler"),
 ("40", 53.92, 54.68, "one beat", "INT. LIVING ROOM - ROLLER",
  "A painter rolls the wall cream white, straight over the lavender splatter.",
  ["loc_stofa"], "50mm f/2.8 locked on the wall",
  "@loc_stofa. A painter in white overalls rolls warm cream paint onto the wall in one long smooth stroke, covering a splatter of lavender paint, close on the roller, warm light.", "K", "ROLLER on 53.92", "Málari"),
 ("41", 54.68, 55.43, "one beat", "INT. LIVING ROOM - CURTAINS",
  "A curtain fitter clicks the new rail in; new linen curtains swoop open.",
  ["loc_stofa"], "35mm f/4 locked",
  "@loc_stofa. A curtain fitter on a stepladder clicks a new white curtain rail into its bracket above the window, then pulls the new pale linen curtains open in one smooth swoop, warm light flooding in.", "K", "CLICK, swoosh", "Gluggatjöld"),
 ("42", 55.43, 56.15, "one beat", "INT. KITCHEN - DRAIN",
  "A drain tech's hose in the plughole; the sink drains clear. Hrefna sips a glass of water.",
  ["loc_eldhus","hrefna"], "35mm f/2.8 high angle",
  "@loc_eldhus. A drain technician in orange overalls pulls a black hose out of the sink plughole, the murky water swirls away and the sink drains clear, beside him @hrefna sips from a glass of clear water with a satisfied nod, warm window light.", "K", "SLURP drain on 55.43", "Stíflulosun"),
 ("43", 56.15, 56.87, "one beat", "INT. KITCHEN - ALARM",
  "A new smoke alarm clicks onto the ceiling, green light blinks. A fire blanket goes on the wall.",
  ["loc_eldhus"], "35mm f/2.8 low angle up",
  "@loc_eldhus. Low angle up, a fire-safety technician clicks a new white smoke alarm onto the kitchen ceiling and its small green light blinks once, then hangs a red fire blanket pouch on the wall beside the stove.", "K", "CLICK, beep", "Eldvarnir"),
 ("44", 56.87, 57.59, "one beat", "INT. LIVING ROOM - FLOOR",
  "A floor layer taps the loose board down. Kári walks over it: nothing happens. Relief.",
  ["loc_stofa","kari"], "35mm f/4 floor-level",
  "@loc_stofa. Floor-level shot, a floor layer taps a loose parquet board flat with a rubber mallet, @kari steps over the same board carefully and nothing happens, he exhales with relief.", "K", "MALLET TAP on 56.87", "Gólfefni"),
 ("45", 57.59, 58.28, "one beat", "EXT. SIDE DECK - NEW PLANK",
  "A carpenter nails the last new plank; Kári bounces on it and grins.",
  ["loc_hus","kari"], "35mm f/4 low",
  "@loc_hus, the side deck now with fresh pale new planks, a carpenter drives the last nail with a hammer, @kari bounces on the new plank with both feet and grins, afternoon sun.", "K", "HAMMER on 57.59", "Pallar"),
 ("46", 58.28, 59.77, "QUARTER-BEAT RUN: 58.28 58.46 58.65 58.84 59.02 59.21 59.40 59.58", "RAPID FIX MONTAGE",
  "Eight cuts of ~0.19 s each, like the reference's last run: thermostat dial turns up; bare feet on a warm floor; Snati rinsed clean in the bath, shakes; Ási sticks a magnet on the fridge; a floor lamp switches on; the key goes on a hook; the bowl goes back in the cupboard; the SVIF book lands on the coffee table.",
  ["snati","asi","prop_b-klingur"], "mixed, all locked, each a single action",
  "Eight separate stills to animate: (a) a hand turns a white floor-heating thermostat dial clockwise; (b) bare feet step onto warm parquet, toes curling; (c) @snati in a bathtub being rinsed with a shower head, lavender paint running off, then shaking; (d) @asi slaps a magnet onto the fridge door; (e) a floor lamp switches on in a warm living room; (f) a brass key hung on a wooden hook; (g) a white bowl placed on a cupboard shelf; (h) @prop_b-klingur set down on a wooden coffee table.", "K", "a tick on every quarter beat", "Gólfhiti, Þrif"),
 ("47", 59.77, 61.32, "resolve", "INT. LIVING ROOM - EVENING",
  "Warm. Lights on, TV on, new curtains, Snati clean and asleep, Kári's hair flat, Hrefna's head on his shoulder, Ási reading the book. Same framing as the family portrait in shot 30.",
  ["loc_stofa","hrefna","kari","asi","snati","prop_b-klingur"], "35mm f/4 locked, identical frame to shot 30",
  "@loc_stofa. Same symmetrical locked wide as before, now the room is finished and warm: the pendant lamp glowing, new pale linen curtains, a clean window, @hrefna rests her head on the shoulder of @kari whose hair is flat and dry, @asi sits cross-legged reading @prop_b-klingur, @snati clean and asleep across their feet, the TV glowing, evening blue outside the window.", "K", "music resolves, TV murmur, dog snore", ""),
 ("48", 61.32, 63.62, "outro, quiet", "EXT. HOUSE - DUSK, THE BOOK FLIES",
  "Wide of the house at dusk, windows glowing. A lavender book flutters down out of the sky like the reference newspaper.",
  ["loc_hus","prop_b-klingur"], "24mm f/8 locked, tilt up to the sky then down",
  "@loc_hus at dusk, the windows glowing warm from inside, a square lavender booklet @prop_b-klingur flutters down out of the pale evening sky turning slowly, drifting toward the front door, the camera tilts gently to follow it.", "S", "wind, paper flutter", ""),
 ("49", 63.62, 65.13, "loop back to shot 1", "EXT. GATE - THE BOOK LANDS",
  "The book lands on the doormat. The family walks into frame from the right toward the gate. Match-cut to shot 1: the loop closes.",
  ["loc_hus","prop_b-klingur","hrefna","kari","asi","snati"], "24mm f/8, the exact framing of shot 1",
  "@loc_hus, the exact wide framing of the opening shot, @prop_b-klingur drops the last metre and lands flat on the brown doormat, @hrefna, @kari, @asi and @snati walk into frame from the right and stop at the garden gate looking up at the house, warm afternoon sun from the left.", "K", "paper slap, then the first bar of the track again", ""),
]
